name: continuously run gitgat

on:
  schedule:
  - cron: "0 23 * * *"
  
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env: 
      GITHUB_SECRET : ${{secrets.GH_SECRET}}
    steps:
    
    # checkout in order to have state
    - uses: actions/checkout@v3
    
    # run gitgat
    - name: run GitGat
      run: docker run -e "$GITHUB_SECRET" scribesecurity/gitgat:latest  data.gh.post_gist
      
      
    
    
