name: continuously run gitgat

on:
  schedule:
  - cron: "0 23 * * *"
  
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env: 
      GITHUB_SECRET : ${{secrets.GITHUB_SECRET}}
    steps:
    
    # checkout in order to have state
    - uses: actions/checkout@v3
    
    name: run gensbom
    
    
