name: continuously run gitgat

on:
  schedule:
  - cron: "0 23 * * *"
  
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env: 
      GITHUB_SECRET : ${{secrets.GITHUB_SECRET}}
    steps:
    
    # checkout in order to have state
    - uses: actions/checkout@v3
    
    # run gensbom
    - name: run gensbom
      run: docker run -e GITHUB_SECRET -v {$pwd}:/var/opt/opascribesecurity/gitgat:latest data.github.report.print_report 2> report.md
      
    # Upload report to artifacts
    - name: uplaod report.md as artifact
      uses: actions/upload-artifact@v3
      with:
          name: Checkout sbom
          path: report.md
      
    
    
